nyaa/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from nyaa_django import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',views.main),
    url(r'^search',views.main),
    url(r'^view/([0-9]+)',views.view),
    url(r'^upload/',views.upload),
    url(r'^user/', include('registration.backends.hmac.urls')),
    url(r'^$',views.index)
]

pynyaa/models/torrents.py
from urllib.parse import quote

from .. import db


class Torrent(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1024), nullable=False)
    hash = db.Column(db.String(40), index=True, nullable=False)

    is_sqlite_import = db.Column(db.Boolean, default=False)

    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    category = db.relationship('Category', backref='torrents')

    sub_category_id = db.Column(db.Integer, db.ForeignKey('sub_category.id'))
    sub_category = db.relationship('SubCategory', backref='torrents')

    status_id = db.Column(db.Integer, db.ForeignKey('status.id'))
    status = db.relationship('Status', backref='torrents')

    date = db.Column(db.DateTime(True), index=True)
    downloads = db.Column(db.Integer, index=True)
    stardom = db.Column(db.Integer, index=True)
    filesize = db.Column(db.BigInteger, index=True)

    description = db.Column(db.Text)
    website_link = db.Column(db.String(1024))

    t_creation_date = db.Column(db.DateTime(True))
    t_created_by = db.Column(db.String(255))
    t_comment = db.Column(db.Text)
    t_announce = db.Column(db.Text)
    files = db.relationship('File', backref='torrent')

    @property
    def cat_url_param(self):
        return f'{self.category_id}_{self.sub_category_id}'

    @property
    def magnet(self):
        return f'magnet:?xt=urn:btih:{self.hash.lower()}' \
               f'&dn={quote(self.name)}'


class Category(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1024))


class SubCategory(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1024))

    parent_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    parent = db.relationship('Category', backref='sub_categories')

    @property
    def image_url(self):
        return f'img/torrents/{self.id}.png'


class Status(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    label = db.Column(db.String(50))

    @property
    def css_class(self):
        if self.name == 'a+':
            return 'aplus'
        return self.name


class UserStatus(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), unique=True)

    status_id = db.Column(db.Integer, db.ForeignKey('user_status.id'))
    status = db.relationship('UserStatus', backref='users')


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text)
    date = db.Column(db.DateTime(True))
    av = db.Column(db.String(255))

    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    user = db.relationship('User', backref='comments')

    torrent_id = db.Column(db.Integer, db.ForeignKey('torrent.id'))
    torrent = db.relationship('Torrent', backref='comments')


class File(db.Model):
    path = db.Column(db.String(1024), primary_key=True)
    torrent_id = db.Column(db.Integer, db.ForeignKey('torrent.id'), primary_key=True)
    size = db.Column(db.Integer)

pynyaa/views/api.py
from flask import Blueprint, abort, jsonify

from .. import models, utils


api = Blueprint('api', __name__)


@api.route('/filelist/<int:torrent_id>')
def filelist(torrent_id):
    torrent = models.Torrent.query.filter_by(id=torrent_id).first()
    if torrent is None:
        return abort(404)
    files = []
    for file in torrent.files:
        files.append(dict(
            path=file.path,
            size=file.size,
            pretty_size=utils.pretty_size(file.size),
        ))
    return jsonify(
        id=torrent.id,
        files=files
    )

pynyaa/views/errors.py
from flask import render_template


def page_not_found(e):
    return render_template('404.html'), 404

pynyaa/templates/faq.html
{% extends "base.html" %}

{% block title %}FAQ{% endblock %}

{% block content %}
    <div class="blockBody">
        <h1>There is nothing here</h1>
    </div>
{% endblock %}

pynyaa/templates/view.html
{% extends "base.html" %}
{% block title %}{{ torrent.name }}{% endblock %}
{% block container_class %}cont-view{% endblock %}

{% block content %}
    <div class="blockBody">
        <hr>
        <table class="table table-borderless">
            <colgroup>
                <col width="10%" />
                <col/>
            </colgroup>
            <tr class="{{ torrent.status.css_class }}"></tr>
            <tr>
                <th>Name</th>
                <td>{{ torrent.name }}</td>
            </tr>
            <tr>
                <th>Hash</th>
                <td>{{ torrent.hash }}</td>
            </tr>
            <tr>
                <th>Upload date</th>
                <td>
                    <time datetime="{{ torrent.date.strftime('%Y-%m-%dT%H:%M:%S%z') }}">
                        {{ torrent.date.strftime('%Y-%m-%d %H:%M%z') }}
                    </time>
                </td>
            </tr>
            <tr>
                <th>Size</th>
                <td>{{ torrent.filesize|pretty_size }}</td>
            </tr>
            <tr>
                <th>Links</th>
                <td><a aria-label="Magnet Button" href="{{ torrent.magnet }}" type="button"
                       class="btn btn-success download-btn">
                    <span class="glyphicon glyphicon-magnet" aria-hidden="true"></span>
                    Download!</a>
                </td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ torrent.description }}</td>
            </tr>
        </table>

    {% if not torrent.is_sqlite_import %}
        <hr>
        <h2>Torrent details</h2>
        <table class="table table-borderless">
        <colgroup>
            <col width="10%" />
            <col/>
        </colgroup>
        <tr>
            <th>Created by</th>
            <td>{{ torrent.t_created_by }}</td>
        </tr>
        <tr>
            <th>Creation date</th>
            <td>
                <time datetime="{{ torrent.t_creation_date.strftime('%Y-%m-%dT%H:%M:%S%z') }}">
                    {{ torrent.t_creation_date.strftime('%Y-%m-%d %H:%M%z') }}
                </time>
            </td>
        </tr>
        <tr>
            <th>Comment</th>
            <td>{{ torrent.t_comment }}</td>
        </tr>
        <tr>
            <th>Announce</th>
            <td>{{ torrent.t_announce }}</td>
        </tr>
        </table>
    {% endif %}

    <hr>
    <h2>File list</h2>
    {% if not torrent.is_sqlite_import %}
        <a href="{{ url_for('api.filelist', torrent_id=torrent.id) }}"
           class="btn btn-default" data-toggle="file-list"
           data-target="#file-list">Show file list</a>
        <table id="file-list" class="table table-striped table-condensed hidden">
            <colgroup>
                <col width="100%" />
                <col width="100" />
            </colgroup>
            <thead>
                <tr>
                    <th>Path</th>
                    <th>Size</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Path</th>
                    <th>Size</th>
                </tr>
            </tfoot>
            <tbody></tbody>
        </table>
    {% else %}
        <div class="text-center">
            <em>No data available</em>
        </div>
    {% endif %}

    {% if torrent.comments %}
        <hr>
        <h2>Comments</h2>


        {% for comment in torrent.comments %}
            <div class="comment" id="c{{ comment.id }}">
                <div class="author">
                    <strong>{{ comment.user.name }}</strong>
                </div>
                <div class="datetime">
                    <em>
                        <time datetime="{{ comment.date.strftime('%Y-%m-%dT%H:%M:%S%z') }}">
                            {{ comment.date.strftime('%Y-%m-%d %H:%M%z') }}
                        </time>
                    </em>
                </div>
                <div class="text">{{ comment.text|safe }}</div>
            </div>
            <hr>
        {% endfor %}
    {% endif %}
    </div>
{% endblock %}